name: .NET CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Сборка и тестирование
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Получаем код из репозитория
      - name: Checkout repository
        uses: actions/checkout@v4

      # Шаг 2: Устанавливаем .NET
      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      # Шаг 3: Восстанавливаем зависимости
      - name: Restore dependencies
        run: |
        dotnet restore calculator/calculator.csproj
        dotnet restore calculator.tests/calculator.tests.csproj

      # Шаг 4: Собираем проект
      - name: Build
        run: dotnet build calculator/calculator.csproj --no-restore --configuration Release

      # Шаг 5: Запускаем тесты
      - name: Test
        run: dotnet test calculator.tests/calculator.tests.csproj --no-restore --verbosity normal
