name: .NET CI Pipeline
on:
push:
branches: [ "main" ]
pull_request:
branches: [ "main" ]
jobs:
jobs:
build:
name: I Сборка и тестирование
runs-on: ubuntu-latest
steps:
- name:
uses: actions/checkout@v4
uses: actions/setup-dotnet@v3
with:
dotnet-version: '8.x'
- name:
run: dotnet restore
- namе: Собираем проект
run: dotnet build -- no-restore --
configuration Release
- name: / Запускаем тесты
run: dotnet test -- no-build --
verbosity normal
Загружаем код
- name:
